### ISSUE TITLE
Add Instructions for Running Slasher + Motivations

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/documentation#59]
We should use our docs portal for all our READMEs and key information for Prysm. Currently, we have instructions for running our slasher [here](https://github.com/prysmaticlabs/prysm/tree/master/slasher) but we should create a dedicated item in the sidebar of the docs portal.

**Comment by har00ga** [comment]
I take it this is something that should go under 'how Prysm works'?

**Comment by prestonvanloon** [comment]
That sounds like a good place to put this documentation. Thanks

>

**Comment by wgknowles** [comment]
Exact syntax to run slasher will vary by OS & again by prysm.sh/prysm.bat/docker/bazel.  Might make more sense having a "Run Slasher" page per OS?

**Comment by har00ga** [comment]
Imho it doesn't warrant it's own page with 1 command, better to just bundle it with existing pages and link back to a slasher specific section is usage to explain motive.

**Comment by wgknowles** [comment]
Also need an update to list available flags: https://docs.prylabs.network/docs/prysm-usage/parameters/

**Comment by wgknowles** [comment]
Flags for Slasher: 

cmd OPTIONS:
  --clear-db                     Prompt for clearing any previously stored data at the data directory (default: false)
  --config-file value            The filepath to a yaml file with flag values
  --datadir value                Data directory for the databases and keystore (default: "/Users/zypherx/Library/Eth2")
  --enable-tracing               Enable request tracing. (default: false)
  --force-clear-db               Clear any previously stored data at the data directory (default: false)
  --log-file value               Specify log file name, relative or absolute
  --log-format value             Specify log formatting. Supports: text, json, fluentd. (default: "text")
  --monitoring-port value        Port used to listening and respond metrics for prometheus. (default: 8082)
  --trace-sample-fraction value  Indicate what fraction of p2p messages are sampled for tracing. (default: 0.2)
  --tracing-endpoint value       Tracing endpoint defines where beacon chain traces are exposed to Jaeger. (default: "http://127.0.0.1:14268/api/traces")
  --tracing-process-name value   The name to apply to tracing tag "process_name"
  --verbosity value              Logging verbosity (trace, debug, info=default, warn, error, fatal, panic) (default: "info")

debug OPTIONS:
  --cpuprofile value      Write CPU profile to the given file
  --memprofilerate value  Turn on memory profiling with the given rate (default: 524288)
  --pprof                 Enable the pprof HTTP server (default: false)
  --pprofaddr value       pprof HTTP server listening interface (default: "127.0.0.1")
  --pprofport value       pprof HTTP server listening port (default: 6060)
  --trace value           Write execution trace to the given file

slasher OPTIONS:
  --beacon-rpc-provider value  Beacon node RPC provider endpoint (default: "localhost:4000")
  --beacon-tls-cert value      Certificate for secure beacon gRPC connection. Pass this in order to use beacon gRPC securely.
  --rebuild-span-maps          Rebuild span maps from indexed attestations in db (default: false)
  --rpc-port value             RPC port exposed by the slasher (default: 5000)
  --tls-key value              Key for secure gRPC. Pass this and the tls-cert flag in order to use gRPC securely.

**Comment by wgknowles** [comment]
Seems that --tls-cert may be missing?
